name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependency
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
